version: "3.8"

services:
  reserva-tenis:
    image: mcr.microsoft.com/playwright/python:v1.44.0-jammy
    container_name: reserva-tenis
    working_dir: /app
    volumes:
      - ./:/app
      - ./screenshots:/app/screenshots
    env_file:
      - .env
    command: >
      bash -c "pip install playwright python-dotenv &&
               playwright install chromium &&
               python reserva_final.py"
    restart: "no"